<div>
    <style>
        #consultationSummaryModal .modal-dialog{max-width:720px}#consultationSummaryModal .modal-content{overflow:hidden;border:0;border-radius:22px;background:#f8fafc;box-shadow:0 28px 80px rgba(15,23,42,.24)}
        #consultationSummaryModal .csm-hero{padding:23px 25px;color:#fff;background:linear-gradient(135deg,#075985,#0369a1 52%,#0891b2)}#consultationSummaryModal .csm-hero-row{display:flex;align-items:center;gap:13px}#consultationSummaryModal .csm-icon{display:flex;align-items:center;justify-content:center;width:48px;height:48px;flex:none;border-radius:15px;background:rgba(255,255,255,.16);font-size:21px}#consultationSummaryModal h5{margin:0;color:#fff;font-size:18px;font-weight:800}#consultationSummaryModal .csm-hero p{margin:5px 0 0;color:rgba(255,255,255,.8);font-size:12px}#consultationSummaryModal .csm-close{margin-right:auto;width:36px;height:36px;border:0;border-radius:11px;background:rgba(255,255,255,.15);color:#fff}
        #consultationSummaryModal .modal-body{padding:22px}#consultationSummaryModal .csm-people{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}#consultationSummaryModal .csm-person{padding:12px 14px;border:1px solid #e4e7ec;border-radius:13px;background:#fff}#consultationSummaryModal .csm-person small{display:block;margin-bottom:3px;color:#98a2b3;font-size:11px}#consultationSummaryModal .csm-person strong{display:block;color:#344054;font-size:13px}#consultationSummaryModal .csm-person span{display:block;margin-top:4px;color:#667085;font-size:11px}
        #consultationSummaryModal .csm-state{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px;padding:14px 16px;border-radius:14px;background:#fff;border:1px solid #e4e7ec}#consultationSummaryModal .csm-state-copy strong{display:block;color:#1d2939;font-size:14px}#consultationSummaryModal .csm-state-copy small{display:block;margin-top:3px;color:#667085;font-size:11.5px}#consultationSummaryModal .csm-badge{display:inline-flex;align-items:center;gap:6px;padding:6px 10px;border-radius:9px;font-size:11.5px;font-weight:700;white-space:nowrap}.csm-badge-success{background:#ecfdf3;color:#067647}.csm-badge-warning{background:#fffaeb;color:#b54708}.csm-badge-danger{background:#fef3f2;color:#b42318}
        #consultationSummaryModal .csm-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}#consultationSummaryModal .csm-stat{padding:13px 8px;border:1px solid #e4e7ec;border-radius:13px;background:#fff;text-align:center}#consultationSummaryModal .csm-stat i{display:block;margin-bottom:7px;color:#0284c7;font-size:16px}#consultationSummaryModal .csm-stat strong{display:block;color:#1d2939;font-size:15px;direction:ltr}#consultationSummaryModal .csm-stat small{display:block;margin-top:3px;color:#667085;font-size:10.5px}#consultationSummaryModal .csm-last{display:flex;align-items:center;gap:9px;margin-top:12px;padding:11px 13px;border-radius:11px;background:#eef8ff;color:#344054;font-size:11.5px}#consultationSummaryModal .csm-last i{color:#0284c7}
        #consultationSummaryModal .csm-checks{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:14px}.csm-check{display:flex;align-items:center;gap:10px;padding:11px 13px;border:1px solid #fda29b;border-radius:12px;background:#fff4f2;color:#b42318}.csm-check.is-done{border-color:#abefc6;background:#ecfdf3;color:#067647}.csm-check i{font-size:17px}.csm-check strong{display:block;font-size:12.5px}.csm-check small{display:block;margin-top:2px;font-size:10.5px;color:#667085}
        #consultationSummaryModal .csm-finance{display:grid;grid-template-columns:130px 1fr;gap:16px;align-items:center;margin-top:14px;padding:16px;border:1px solid #d1e9ff;border-radius:15px;background:linear-gradient(135deg,#fff,#f5fbff)}.csm-chart{position:relative;width:112px;height:112px;margin:auto;border-radius:50%;box-shadow:0 5px 18px rgba(15,23,42,.1)}.csm-chart:after{content:"";position:absolute;inset:18px;border-radius:50%;background:#fff}.csm-chart-center{position:absolute;z-index:1;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}.csm-chart-center strong{font-size:12px;color:#1d2939}.csm-chart-center small{font-size:9.5px;color:#667085}.csm-finance-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.csm-money{padding:9px 10px;border-radius:10px;background:#fff;border:1px solid #eaecf0}.csm-money span{display:block;color:#667085;font-size:10px}.csm-money strong{display:block;margin-top:3px;color:#1d2939;font-size:12px}.csm-dot{display:inline-block;width:7px;height:7px;margin-left:4px;border-radius:50%}
        #consultationSummaryModal .modal-footer{justify-content:space-between;padding:14px 22px;border-top:1px solid #eaecf0;background:#fff}#consultationSummaryModal .csm-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;height:39px;padding:0 15px;border:1px solid #d0d5dd;border-radius:10px;background:#fff;color:#344054;font-size:12.5px;font-weight:700}.csm-btn-primary{border-color:#0369a1;background:#0369a1;color:#fff}
        @media(max-width:576px){#consultationSummaryModal .csm-people,#consultationSummaryModal .csm-stats,#consultationSummaryModal .csm-checks{grid-template-columns:1fr 1fr}#consultationSummaryModal .csm-state{align-items:flex-start;flex-direction:column}#consultationSummaryModal .csm-finance{grid-template-columns:1fr}.csm-finance-grid{grid-template-columns:1fr 1fr}}
    </style>
    <div wire:ignore.self class="modal fade" id="consultationSummaryModal" tabindex="-1" aria-labelledby="consultationSummaryTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content">
        <div class="csm-hero"><div class="csm-hero-row"><span class="csm-icon"><i class="fa fa-phone"></i></span><div><h5 id="consultationSummaryTitle">جزئیات مشاوره تلفنی</h5><p>اطلاعات مهم نوبت در یک نگاه</p></div><button type="button" class="csm-close" data-bs-dismiss="modal" aria-label="بستن"><i class="fa fa-times"></i></button></div></div>
        <div class="modal-body">@if(!empty($consultationSummary))
            @php
                $financeTotal = max(1, (int)$consultationSummary['appointment_amount']);
                $refundPercent = min(100, max(0, round($consultationSummary['refund_amount'] * 100 / $financeTotal, 1)));
                $practitionerPercent = min(100 - $refundPercent, max(0, round($consultationSummary['practitioner_amount'] * 100 / $financeTotal, 1)));
                $practitionerEnd = $refundPercent + $practitionerPercent;
                $financeChart = $consultationSummary['appointment_amount'] > 0
                    ? "conic-gradient(#ef4444 0 {$refundPercent}%,#10b981 {$refundPercent}% {$practitionerEnd}%,#38bdf8 {$practitionerEnd}% 100%)"
                    : '#e5e7eb';
            @endphp
            <div class="csm-people"><div class="csm-person"><small>بیمار</small><strong>{{ $consultationSummary['patient'] }}</strong><span>کد پیگیری: {{ $consultationSummary['tracking_code'] }}</span></div><div class="csm-person"><small>پزشک / مشاور</small><strong>{{ $consultationSummary['doctor'] }}</strong><span>{{ $consultationSummary['date'] }}</span></div></div>
            <div class="csm-checks"><div class="csm-check {{ $consultationSummary['completed'] ? 'is-done' : '' }}"><i class="fa {{ $consultationSummary['completed'] ? 'fa-check-circle' : 'fa-exclamation-circle' }}"></i><div><strong>{{ $consultationSummary['completed'] ? 'اتمام ویزیت ثبت شده' : 'اتمام ویزیت ثبت نشده' }}</strong><small>وضعیت پرونده مشاوره</small></div></div><div class="csm-check {{ $consultationSummary['financial_calculated'] ? 'is-done' : '' }}"><i class="fa {{ $consultationSummary['financial_calculated'] ? 'fa-check-circle' : 'fa-exclamation-circle' }}"></i><div><strong>{{ $consultationSummary['financial_status'] }}</strong><small>وضعیت محاسبه و تسویه مالی</small></div></div></div>
            <div class="csm-state"><div class="csm-state-copy"><strong>{{ $consultationSummary['completed'] ? 'مشاوره پایان یافته است' : 'پرونده مشاوره هنوز باز است' }}</strong><small>{{ $consultationSummary['answered'] ? 'حداقل یک تماس پاسخ داده شده ثبت شده است.' : 'هنوز تماس پاسخ‌داده‌شده‌ای ثبت نشده است.' }}</small></div><span class="csm-badge {{ $consultationSummary['answered'] ? 'csm-badge-success' : 'csm-badge-danger' }}"><i class="fa {{ $consultationSummary['answered'] ? 'fa-check-circle' : 'fa-phone-square' }}"></i>{{ $consultationSummary['answered'] ? 'پاسخ داده' : 'بدون پاسخ' }}</span></div>
            <div class="csm-stats"><div class="csm-stat"><i class="fa fa-phone"></i><strong>{{ $consultationSummary['calls_count'] }}</strong><small>کل تماس‌ها</small></div><div class="csm-stat"><i class="fa fa-check"></i><strong>{{ $consultationSummary['answered_count'] }}</strong><small>پاسخ‌داده‌شده</small></div><div class="csm-stat"><i class="fa fa-phone-square"></i><strong>{{ $consultationSummary['unanswered_count'] }}</strong><small>بی‌پاسخ در موعد</small></div><div class="csm-stat"><i class="fa fa-clock-o"></i><strong>{{ $consultationSummary['talk_duration'] }}</strong><small>مجموع مکالمه</small></div></div>
            <div class="csm-finance"><div class="csm-chart" style="background:{{ $financeChart }}"><div class="csm-chart-center"><strong>{{ number_format($consultationSummary['appointment_amount']) }}</strong><small>تومان</small></div></div><div class="csm-finance-grid"><div class="csm-money"><span><i class="csm-dot" style="background:#ef4444"></i>میزان بازگشتی</span><strong>{{ number_format($consultationSummary['refund_amount']) }} تومان</strong></div><div class="csm-money"><span><i class="csm-dot" style="background:#10b981"></i>سهم مشاور</span><strong>{{ number_format($consultationSummary['practitioner_amount']) }} تومان</strong></div><div class="csm-money"><span><i class="csm-dot" style="background:#38bdf8"></i>سهم مجموعه</span><strong>{{ number_format($consultationSummary['platform_amount']) }} تومان</strong></div><div class="csm-money"><span>مبلغ واقعی نوبت</span><strong>{{ number_format($consultationSummary['appointment_amount']) }} تومان</strong></div></div></div>
            @if($consultationSummary['early_count'])<div class="csm-last"><i class="fa fa-info-circle"></i>{{ $consultationSummary['early_count'] }} تماس زودهنگام خارج از بازه نوبت ثبت شده است.</div>@endif
            <div class="csm-last"><i class="fa fa-history"></i>آخرین تماس: <bdi>{{ $consultationSummary['last_call_at'] }}</bdi></div>
        @endif</div>
        <div class="modal-footer"><button type="button" class="csm-btn" data-bs-dismiss="modal">بستن</button>@if(!empty($consultationSummary['details_url']))<a class="csm-btn csm-btn-primary" href="{{ $consultationSummary['details_url'] }}"><i class="fa fa-external-link"></i>مشاهده جزئیات کامل</a>@endif</div>
    </div></div></div>
</div>
