@once
    <style>
        #financialSummaryModal .modal-dialog{max-width:700px}#financialSummaryModal .modal-content{overflow:hidden;border:0;border-radius:22px;background:#f8fafc;box-shadow:0 28px 80px rgba(15,23,42,.24)}
        #financialSummaryModal .fsm-hero{padding:23px 25px;color:#fff;background:linear-gradient(135deg,#065f46,#059669 55%,#10b981)}#financialSummaryModal .fsm-hero-row{display:flex;align-items:center;gap:13px}#financialSummaryModal .fsm-icon{display:flex;align-items:center;justify-content:center;width:48px;height:48px;flex:none;border-radius:15px;background:rgba(255,255,255,.17);font-size:21px}#financialSummaryModal h5{margin:0;color:#fff;font-size:18px;font-weight:800}#financialSummaryModal .fsm-hero p{margin:5px 0 0;color:rgba(255,255,255,.84);font-size:12px}#financialSummaryModal .fsm-close{margin-right:auto;width:36px;height:36px;border:0;border-radius:11px;background:rgba(255,255,255,.15);color:#fff}
        #financialSummaryModal .modal-body{padding:22px}#financialSummaryModal .fsm-state{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px;padding:14px 16px;border:1px solid #d1fae5;border-radius:14px;background:#fff}.fsm-state strong{display:block;color:#1d2939;font-size:14px}.fsm-state small{display:block;margin-top:4px;color:#667085;font-size:11.5px}.fsm-badge{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:9px;background:#fffaeb;color:#b54708;font-size:11.5px;font-weight:800;white-space:nowrap}.fsm-badge.is-settled{background:#ecfdf3;color:#067647}
        #financialSummaryModal .fsm-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.fsm-item{padding:14px;border:1px solid #e4e7ec;border-radius:13px;background:#fff}.fsm-item span{display:block;margin-bottom:5px;color:#667085;font-size:11px}.fsm-item strong{display:block;color:#1d2939;font-size:14px}.fsm-item.is-refund strong{color:#b42318}.fsm-item.is-income strong{color:#067647}.fsm-time{display:flex;gap:18px;margin-top:13px;padding:12px 14px;border-radius:12px;background:#ecfdf3;color:#065f46;font-size:12px}.fsm-time i{margin-left:5px}
        #financialSummaryModal .modal-footer{justify-content:space-between;padding:14px 22px;border-top:1px solid #eaecf0;background:#fff}.fsm-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;height:39px;padding:0 15px;border:1px solid #d0d5dd;border-radius:10px;background:#fff;color:#344054;font-size:12.5px;font-weight:700}.fsm-btn-primary{border-color:#059669;background:#059669;color:#fff}
        @media(max-width:576px){#financialSummaryModal .fsm-grid{grid-template-columns:1fr 1fr}.fsm-state{align-items:flex-start!important;flex-direction:column}.fsm-time{flex-direction:column;gap:5px}}
    </style>
@endonce
<div wire:ignore.self class="modal fade" id="financialSummaryModal" tabindex="-1" aria-labelledby="financialSummaryTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
    <div class="fsm-hero"><div class="fsm-hero-row"><span class="fsm-icon"><i class="fa fa-credit-card"></i></span><div><h5 id="financialSummaryTitle">وضعیت مالی نوبت</h5><p>خلاصه محاسبه، تسویه و سهم‌ها در یک نگاه</p></div><button type="button" class="fsm-close" data-bs-dismiss="modal" aria-label="بستن"><i class="fa fa-times"></i></button></div></div>
    <div class="modal-body">@if(!empty($financialSummary))
        <div class="fsm-state"><div><strong>{{ $financialSummary['patient'] }} · {{ $financialSummary['doctor'] }}</strong><small>نوبت #{{ $financialSummary['tracking_code'] }}</small></div><span class="fsm-badge {{ $financialSummary['settled'] ? 'is-settled' : '' }}"><i class="fa {{ $financialSummary['settled'] ? 'fa-check-circle' : 'fa-clock-o' }}"></i>{{ $financialSummary['state'] }}</span></div>
        <div class="fsm-grid">
            <div class="fsm-item"><span>مبلغ واقعی نوبت</span><strong>{{ number_format($financialSummary['appointment_amount']) }} تومان</strong></div>
            <div class="fsm-item"><span>مبلغ مصرف‌شده</span><strong>{{ number_format($financialSummary['used_amount']) }} تومان</strong></div>
            <div class="fsm-item is-refund"><span>{{ $financialSummary['refund_label'] }}</span><strong>{{ number_format($financialSummary['refund_amount']) }} تومان</strong></div>
            <div class="fsm-item is-income"><span>خالص پس از بازگشت</span><strong>{{ number_format($financialSummary['net_amount']) }} تومان</strong></div>
            <div class="fsm-item"><span>سهم مشاور</span><strong>{{ number_format($financialSummary['practitioner_amount']) }} تومان</strong></div>
            <div class="fsm-item"><span>سهم مجموعه</span><strong>{{ number_format($financialSummary['platform_amount']) }} تومان</strong></div>
        </div>
        @if($financialSummary['reserved_minutes'] > 0)<div class="fsm-time"><span><i class="fa fa-calendar-check-o"></i>مدت رزرو: <strong>{{ $financialSummary['reserved_minutes'] }} دقیقه</strong></span><span><i class="fa fa-clock-o"></i>زمان مالی مؤثر: <strong>{{ $financialSummary['used_minutes'] }} دقیقه</strong></span></div>@endif
    @endif</div>
    <div class="modal-footer"><button type="button" class="fsm-btn" data-bs-dismiss="modal">بستن</button>@if(!empty($financialSummary['details_url']))<a class="fsm-btn fsm-btn-primary" href="{{ $financialSummary['details_url'] }}"><i class="fa fa-external-link"></i>جزئیات کامل مالی</a>@endif</div>
</div></div></div>
