@extends('onlineconsultation::shell')
@section('consultation-title', 'جزئیات تماس')
@section('consultation-description', 'شناسه تماس '.$callLog->call_id)
@section('consultation-header-actions')<a class="oc-btn" href="{{ $callLog->appointment_id ? route('admin.consultation.call-reports.appointment', $callLog->appointment_id) : route('admin.consultation.call-reports.index') }}"><i class="fa-solid fa-arrow-right"></i>بازگشت</a>@endsection
@section('consultation-content')
@php
    $duration = fn ($seconds) => sprintf('%02d:%02d:%02d', intdiv((int) $seconds, 3600), intdiv(((int) $seconds) % 3600, 60), ((int) $seconds) % 60);
    $date = fn ($value) => $value ? verta($value)->format('Y/m/d H:i:s') : '—';
@endphp
<div class="oc-stack">
    <section class="oc-panel"><div class="oc-panel-header"><h2 class="oc-panel-title"><i class="fa-solid fa-phone-volume"></i>نتیجه تماس</h2><span class="oc-badge {{ $callLog->final_result === 'ANSWERED' ? 'oc-badge-success' : 'oc-badge-warning' }}">{{ $callLog->final_result }}</span></div><div class="oc-panel-body oc-detail-grid">
        @foreach([['شناسه تماس',$callLog->call_id],['شناسه نوبت',$callLog->appointment_id ? '#'.$callLog->appointment_id : 'بدون نوبت'],['شماره بیمار',$callLog->patient_phone],['جهت تماس',$callLog->direction],['وضعیت نوبت',$callLog->appointment_state],['نوع اتصال',$callLog->connection_type],['شروع نوبت',$date($callLog->appointment_start_at)],['پایان نوبت',$date($callLog->appointment_end_at)],['داخلی اصلی',$callLog->primary_extension],['مقصد نهایی',$callLog->destination],['مقصد متصل‌شده',$callLog->connected_destination],['شناسه کارشناس',$callLog->operator_id],['پاسخ‌گو',$callLog->operator?->fullName ?: $callLog->responded_by],['قطع‌کننده',$callLog->disconnected_by],['علت قطع',$callLog->hangup_cause]] as [$label,$value])<div><span>{{ $label }}</span><strong class="oc-break">{{ $value ?: '—' }}</strong></div>@endforeach
    </div></section>
    <section class="oc-panel"><div class="oc-panel-header"><h2 class="oc-panel-title"><i class="fa-solid fa-timeline"></i>خط زمانی تماس</h2></div><div class="oc-panel-body"><div class="oc-timeline">
        @foreach([['ورود تماس',$callLog->call_entered_at,'fa-phone'],['شروع شماره‌گیری',$callLog->dial_started_at,'fa-phone-arrow-up-right'],['پاسخ‌گویی',$callLog->answered_at,'fa-headset'],['پایان تماس',$callLog->ended_at,'fa-phone-slash']] as [$label,$value,$icon])<div class="oc-timeline-item {{ $value ? 'is-done' : '' }}"><i class="fa-solid {{ $icon }}"></i><span>{{ $label }}</span><strong><bdi>{{ $date($value) }}</bdi></strong></div>@endforeach
    </div><div class="oc-duration-grid">@foreach([['مدت انتظار',$callLog->wait_duration_seconds],['مدت زنگ‌خوردن',$callLog->ring_duration_seconds],['مدت مکالمه واقعی',$callLog->talk_duration_seconds],['مدت کل تماس',$callLog->total_duration_seconds]] as [$label,$value])<div><span>{{ $label }}</span><strong class="oc-ltr">{{ $duration($value) }}</strong></div>@endforeach</div></div></section>
    <section class="oc-panel"><div class="oc-panel-header"><h2 class="oc-panel-title"><i class="fa-solid fa-route"></i>تلاش‌های اتصال</h2></div>@if(empty($callLog->attempts))<div class="oc-empty"><i class="fa-solid fa-route"></i><h3>مسیر اتصالی ثبت نشده است</h3></div>@else<div class="oc-table-wrap"><table class="oc-table"><thead><tr><th>ترتیب</th><th>نوع</th><th>مقصد</th><th>شروع</th><th>پاسخ</th><th>پایان</th><th>نتیجه</th><th>زنگ</th><th>مکالمه</th></tr></thead><tbody>@foreach($callLog->attempts as $attempt)<tr><td>{{ data_get($attempt,'order','—') }}</td><td>{{ data_get($attempt,'type','—') }}</td><td class="oc-ltr">{{ data_get($attempt,'destination','—') }}</td><td><bdi>{{ data_get($attempt,'dial_started_at','—') }}</bdi></td><td><bdi>{{ data_get($attempt,'answered_at','—') }}</bdi></td><td><bdi>{{ data_get($attempt,'ended_at','—') }}</bdi></td><td>{{ data_get($attempt,'dial_status','—') }}</td><td class="oc-ltr">{{ $duration(data_get($attempt,'ring_duration_seconds',0)) }}</td><td class="oc-ltr">{{ $duration(data_get($attempt,'talk_duration_seconds',0)) }}</td></tr>@endforeach</tbody></table></div>@endif</section>
    @if(!empty($callLog->additional_data))<details class="oc-panel oc-json-panel"><summary><i class="fa-solid fa-code"></i>اطلاعات تکمیلی تماس</summary><pre>{{ json_encode($callLog->additional_data, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre></details>@endif
    <details class="oc-panel oc-json-panel"><summary><i class="fa-solid fa-box-archive"></i>JSON خام دریافتی از سرور VoIP</summary><pre>{{ json_encode($callLog->raw_payload, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre></details>
</div>
@endsection
